#!/bin/sh
### BEGIN INIT INFO
# Provides:          jenkin_initd
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run /opt/jenkin_monitor.sh
### END INIT INFO

. /lib/init/vars.sh
. /lib/lsb/init-functions

PIDFILE=/var/run/jenkin_mon.pid
SERVICE=/opt/jenkin_mon

GPIO_DIR=/sys/class/gpio
GPIO_MAX=39
GPIO_LIST="5 6 9 10 11 13 19 22 26"

gpio_init () {
	for i in $GPIO_LIST; do
		if [ ! -L $GPIO_DIR/gpio$i ]; then
			echo $i > $GPIO_DIR/export
		fi
		echo "out" > $GPIO_DIR/gpio$i/direction
		# Active low
		echo "1" > $GPIO_DIR/gpio$i/value
	done

	return
}

case $1 in
	start)
		if [ -s $PIDFILE ]; then
			echo "Jenkin Jobs Monitoring has already started."
			exit 1
		fi
		gpio_init
		echo "Starting Jenkin Jobs Monitoring daemon..."
		$SERVICE > /dev/null 2>&1 &
		echo $$ > $PIDFILE
		;;
	stop)
		if [ -s $PIDFILE ]; then
			killall $(basename $SERVICE)
			rm -f $PIDFILE
			echo "Starting Jenkin Jobs Monitoring daemon has stopped."
		else
			echo "Jenkin Jobs Monitoring daemon not started."
			exit 1
		fi
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		if [ -s $PIDFILE ]; then
			echo "Jenkin Jobs Monitoring is running."
		else
			echo "Jenkin Jobs Monitoring is not running."
		fi
		;;
	*)
		echo "Use $0 start|stop|restart|status"
		;;
esac

exit 0
#End of file
